_target_: src.models.cifar_module.CIFARLitModule

net:
  _target_: src.models.components.squeeze_net.ModifiedSqueezenet
  num_classes: 100

optimizer:
  name: "RMSProp"
  lr: 0.0001

criterion:
  _target_: torch.nn.CrossEntropyLoss
