_target_: src.datamodules.cifar_datamodule.CIFAR100Datamodule

data_dir: ${data_dir} # data_dir is specified in config.yaml
batch_size: 64
train_val_test_split: [45_000, 5_000, 10_000]
num_workers: 0
pin_memory: False
