_target_: src.datamodules.lrw_datamodule.LRWDataModule

# we loar *.pkl data here
data_dir: ${data_dir}/lrw_crop # data_dir is specified in train/test.yaml
label_path: ${data_dir}/lrw_crop/label_sorted.txt
batch_size: 16
num_workers: 4
pin_memory: True
