_target_: src.datamodules.text_datamodule.NameDataModule

data_dir: ${data_dir}torchdata/names # data_dir is specified in config.yaml
batch_size: 64
train_test_split: [18_063, 2_007]
num_workers: 0
pin_memory: False
